# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_exciting_function": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://stephencwelch.github.io/dsc_ndbev_talk/"

git_url = "https://github.com/stephencwelch/dsc_ndbev_talk/tree/master/"

def custom_doc_links(name): return None
